name: frontend-build-deploy

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "1.0.0"
      ocptoken:
        required: true

jobs:
  call:
    uses: ./.github/workflows/frontend-build-deploy.yml
    with:
      version: ${{ inputs.version }}
      ocptoken: ${{ inputs.ocptoken }}
